#!/usr/bin/python

from networkx import Graph

from vizing.colouring import list_colouring

V = [1, 2, 3, 4]
E = [(1, 2), (1, 4), (2, 3), (3, 4)]
L = {1: [1, 2], 2: [1, 3], 3: [2, 3], 4: [1, 2, 3]}

G = Graph()
G.add_nodes_from(V)
G.add_edges_from(E)

C1 = list_colouring(G, L, model = 'CP')
print C1
