#!/usr/bin/python

# In this demo we find a list-colouring of the four cycle:
#    
# 0 -- 1
# |    |
# 3 -- 2
#
# The list assignment in question assigns colours 1,2 to vertex 0, colours
# 1,3 to vertex 1, colours 2,3 to vertex 2 and colours 1,2,3 to vertex
# 3.

from networkx import cycle_graph

from vizing.colouring import list_colouring

L = {0: [1, 2], 1: [1, 3], 2: [2, 3], 3: [1, 2, 3]}

G = cycle_graph(4)

print list_colouring(G, L)
